In [4]:
import numpy as np


In [6]:
# Importing the NumPy library with an alias 'np'
import numpy as np

# Creating a NumPy array 'x' containing elements 1, 2, 3, and 4
x = np.array([1, 2, 3, 4])

# Printing the original array 'x'
print("Original array:")
print(x)

# Checking if none of the elements in the array 'x' is zero and printing the result
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

# Reassigning array 'x' to a new array containing elements 0, 1, 2, and 3
x = np.array([0, 1, 2, 3])

# Printing the new array 'x'
print("Original array:")
print(x)

# Checking if none of the elements in the updated array 'x' is zero and printing the result
print("Test if none of the elements of the said array is zero:")
print(np.all(x))


Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [7]:
# Checking if any element in the array 'x' is non-zero and printing the result
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))

# Reassigning array 'x' to a new array containing all elements as zero
x = np.array([0, 0, 0, 0])

# Printing the new array 'x'
print("Original array:")
print(x)

# Checking if any element in the updated array 'x' is non-zero and printing the result
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x)) 

Test whether any of the elements of a given array is non-zero:
True
Original array:
[0 0 0 0]
Test whether any of the elements of a given array is non-zero:
False


In [17]:
#Checking the Finiteness of a element - isfinite()

x = np.array([1,3,4,5,5,6,7,7,np.nan])
print(np.isfinite(x))


[ True  True  True  True  True  True  True  True False]


In [19]:
# Testing the given array 'a' element-wise for NaN (Not a Number) and printing the result
print("Test element-wise for NaN:")
print(np.isnan(x)) 

Test element-wise for NaN:
[False False False False False False False False  True]


In [21]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# to create a null vector of size 10 and update the sixth value to 11.
null_array = np.array([np.nan for x in range(10)])
null_array[7] = 11
print(null_array)

[nan nan nan nan nan nan nan 11. nan nan]


In [26]:
array = np.arange(1,10)
range_array = np.arange(12,38); print(range_array)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [31]:
# Reversing a array
range_array = range_array[::-1]
print(range_array)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [33]:
array = np.array([0.5 for x in range(10)], dtype=float)
print(array)

[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


In [39]:
# Creating a 5x5 NumPy array filled with ones
array = np.ones((5,5)) # type: ignore

# Modifying the array 'x' to set the border elements to 1 and inner elements to 0
print("1 on the border and 0 inside in the array")
array[1:-1, 1:-1] = 0
print(array)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
# 8*8 check-board pattern
array_8 = np.zeros((8,8),dtype=int) 
array_8[1::2, ::2] = 1
array_8[::2, 1::2] = 1
print(array_8)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [53]:
# List and Tuple to a NumPy array 
array_list = [5 for x in range(5)]
array_tuple = tuple([6 for x in range(4)])
print(array_list,array_tuple)

# List to Tuple
np_list = np.asarray(array_list)

# Tuple to Array
np_tuple = np.asanyarray(array_tuple)

print(np_list, np_tuple)

[5, 5, 5, 5, 5] (6, 6, 6, 6)
[5 5 5 5 5] [6 6 6 6]


In [55]:
# Appending Values
original_array = np.arange(6,12)
print(f"Original Array : {original_array}")

original_array = np.append(original_array, [x for x in range(13,20)])
print(f"Appended Array : {original_array}")


Original Array : [ 6  7  8  9 10 11]
Appended Array : [ 6  7  8  9 10 11 13 14 15 16 17 18 19]
