In [1]:

import numpy as np
from time import process_time
import random

start_time = process_time()

python_list = [i for i in range(10000)]

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)







0.0


In [2]:
import numpy as np

from time import process_time

np_array = np.array(i for i in range(10000))

start_time = process_time()

np_array = np.array(i+5 for i in range(10000))

end_time = process_time()

print(end_time-start_time)

0.0


Numpy Arrays


In [3]:
#List

list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [4]:

np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [5]:
# Creating a 1 Dimensional Array

np_array = np.array([1,2,3,4])
print(np_array)
np_array.shape

[1 2 3 4]


(4,)

In [6]:
# Creating a 2D array

b = np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# Initial Place Holders by NumPy


x = np.zeros((4,5))
print(x)



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
# creating a numpy array with 1

y = np.ones((7,7))
print(y)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [9]:
# Giving a particular value

h = np.full((5,5), 12)
print(h)

[[12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]]


In [10]:
# Creating a Identity Matrix

v = np.eye(13)
print(v)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
# Creating a NumPy Array with random values

import random


l = random.randint(1,100)

vol2 = random.randint(1,100)
vol1 = random.randint(1,100)

j = np.full((vol1,vol2), l)
print(j)



[[95 95 95 ... 95 95 95]
 [95 95 95 ... 95 95 95]
 [95 95 95 ... 95 95 95]
 ...
 [95 95 95 ... 95 95 95]
 [95 95 95 ... 95 95 95]
 [95 95 95 ... 95 95 95]]


In [12]:
# Creating a Numpy which is evenly spaced -> specifing the number of values required

n = np.linspace(10,10.17,10)
print(n)


[10.         10.01888889 10.03777778 10.05666667 10.07555556 10.09444444
 10.11333333 10.13222222 10.15111111 10.17      ]


In [13]:
# Creating a Numpy which is evenly spaced -> specifing the step

b = np.arange(10,30,4)
print(b)

[10 14 18 22 26]


In [14]:
# Converting a List To Numpy array

list2 = [10,20,30,40,50]
print(type(list2))
np_convert = np.asarray(list2)
type(np_convert)

<class 'list'>


numpy.ndarray

Analysing a Numpy Array

In [15]:
c = np.random.randint(10,100,(5,4))
print(c)

[[59 13 77 66]
 [37 27 57 47]
 [19 43 13 97]
 [26 99 97 92]
 [16 13 70 55]]


In [16]:
# To find an Array Dimension

print(c.shape)

(5, 4)


In [17]:
# To Find Number Of Dimension

print(c.ndim) # Or
print(len(c.shape))

2
2


In [18]:
# To find number of elements in an array

print(c.size) # Or
counter = 1
a = list(c.shape)
for x in a:
  counter *= x
print(counter)

20
20


In [19]:
# Checking the data types of the values in the array

print(c.dtype)

int32


Mathematical Operations Performed On an Np Array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1+list2) # Concantate list (Function Used for this is +)
# Note : In List The Both List Concinnate and gers Extended Not the elements

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [21]:
k = np.random.randint(10,20,(5,6))
b = np.random.randint(1,10,(5,6))
print(k)
print(b)
# But in Numpy Array The elements inside an array gets added (if we take a element 10 and b element 7, a+b means 10+7 = 17 and that is considered an new numpy array)

[[14 14 13 15 10 16]
 [11 12 14 13 10 13]
 [16 13 12 19 19 17]
 [19 17 16 16 10 17]
 [10 14 18 17 18 17]]
[[8 7 4 7 7 4]
 [4 7 6 4 8 2]
 [4 4 9 1 1 8]
 [1 4 8 3 5 7]
 [6 6 6 5 4 2]]


In [22]:
print(k+b)
print(k-b)
print(k*b)
print(k/b)
print(k//b)
print(k%b)

[[22 21 17 22 17 20]
 [15 19 20 17 18 15]
 [20 17 21 20 20 25]
 [20 21 24 19 15 24]
 [16 20 24 22 22 19]]
[[ 6  7  9  8  3 12]
 [ 7  5  8  9  2 11]
 [12  9  3 18 18  9]
 [18 13  8 13  5 10]
 [ 4  8 12 12 14 15]]
[[112  98  52 105  70  64]
 [ 44  84  84  52  80  26]
 [ 64  52 108  19  19 136]
 [ 19  68 128  48  50 119]
 [ 60  84 108  85  72  34]]
[[ 1.75        2.          3.25        2.14285714  1.42857143  4.        ]
 [ 2.75        1.71428571  2.33333333  3.25        1.25        6.5       ]
 [ 4.          3.25        1.33333333 19.         19.          2.125     ]
 [19.          4.25        2.          5.33333333  2.          2.42857143]
 [ 1.66666667  2.33333333  3.          3.4         4.5         8.5       ]]
[[ 1  2  3  2  1  4]
 [ 2  1  2  3  1  6]
 [ 4  3  1 19 19  2]
 [19  4  2  5  2  2]
 [ 1  2  3  3  4  8]]
[[6 0 1 1 3 0]
 [3 5 2 1 2 1]
 [0 1 3 0 0 1]
 [0 1 0 1 0 3]
 [4 2 0 2 2 1]]


Array Manipulation

In [23]:
array = np.random.randint(1,9,(5,6))
print(array)
print(array.shape)

[[8 5 6 5 4 1]
 [1 2 5 8 6 7]
 [7 7 3 3 4 1]
 [1 6 8 8 2 7]
 [7 6 4 2 2 6]]
(5, 6)


In [24]:
# Find Transpose

trans = np.transpose(array)
print(trans)
print(trans.shape) # Or

trans2 = array.T
print(trans2)
print(trans2.shape)

[[8 1 7 1 7]
 [5 2 7 6 6]
 [6 5 3 8 4]
 [5 8 3 8 2]
 [4 6 4 2 2]
 [1 7 1 7 6]]
(6, 5)
[[8 1 7 1 7]
 [5 2 7 6 6]
 [6 5 3 8 4]
 [5 8 3 8 2]
 [4 6 4 2 2]
 [1 7 1 7 6]]
(6, 5)


In [25]:
# Reshaping a array
# this only applies if a*b (old row and column) == c*d (new row and column)
# in thus example , we have array which total elemebts is 30 and it has (5,6) row and column.
# so we can only reshape array which are multiole of 30 . Eg , 5-6 == 3*10
f = array[0][0]
print(f)

j = array.reshape(15,2)
print(j)

8
[[8 5]
 [6 5]
 [4 1]
 [1 2]
 [5 8]
 [6 7]
 [7 7]
 [3 3]
 [4 1]
 [1 6]
 [8 8]
 [2 7]
 [7 6]
 [4 2]
 [2 6]]


In [ ]:
array = np.arange(1,17).reshape(4,4)
print(array)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
